function Figs = plotWaveAmp(result, visibilityOpt, colors)
    % Description: plot amplitude distribution of each cluster
    % Input:
    %     result: struct generated by mysort
    %     visbilityOpt: "on" or "off"
    %     colors: RGB cell array of color of each cluster
    % Output:
    %     Figs: histogram

    narginchk(1, 3);

    if nargin < 2
        visibilityOpt = "on";
    end
        
    if nargin < 3
        colors = generateColorGrad(12, 'red', [1, 4, 7, 10], 'green', [2, 5, 8, 11], 'blue', [3, 6, 9, 12]);
    end

    for eIndex = 1:length(result)
        K = result(eIndex).K;

        % Plot
        Figs(eIndex) = figure;
        maximizeFig(Figs(eIndex));
        set(Figs(eIndex), "Visible", visibilityOpt);

        colorsAll = repmat(reshape(colors, [length(colors), 1]), ceil(K / length(colors)) * length(colors), 1);
        waveAmp = result(eIndex).waveAmp * 1e6; % uV
        binSize = 5; % uV
        edge = (floor(min(waveAmp) / binSize):ceil(max(waveAmp) / binSize)) * binSize;

        for kIndex = 1:K
            temp = mHist(waveAmp(result(eIndex).clusterIdx == kIndex), edge, binSize);
            nFit = 200;
            xSmooth = linspace(min(edge), max(edge), nFit);
            y = interp1(edge, temp, xSmooth, 'cubic');
            plot(xSmooth, y, "Color", colorsAll{kIndex}, "LineWidth", 2, "DisplayName", ['cluster ', num2str(kIndex)]);
            hold on;
            h = plot(edge, temp, ".", "Color", colorsAll{kIndex}, "MarkerSize", 20);
            set(get(get(h, 'Annotation'), 'LegendInformation'), 'IconDisplayStyle', 'off');
        end

        legend;
        xlabel("Spike amplitude (\muV)");
        ylabel("Count");
        title("Spike amplitude distribution of each cluster");
    end

    return;
end
