function selectedIdx = recluster(result, PCShown, colors)
    % Description: plot raster in PCA space, dimensions specified by PCShown
    % Input:
    %     result: struct generated by mysort
    %     PCShown: a vector containing PC dimensions to be shown, length of which is 2(default: [1 2]).
    %     colors: cell array of colors for waveform templates, each specified as
    %             an RGB triplet, a hexadecimal color code, a color name,
    %             or a short name. Same with wave plot color setting (RECOMMENDED).
    % Output:
    %     selectedIdx: points are selected or not
    % Example:
    %     result = mysort(data);
    %     v = validateInput(["non-negative", "integer"], "Please input a cluster number for reclustering: ");
    %     % 1 - Exclude noise
    %     selectedIdx = recluster(result, [1, 2]);
    %     result.clusterIdx(selectedIdx & ~logical(result.noiseClusterIdx)) = v;
    %     % 2 - Multi-dimension selection
    %     selectedIdx1 = recluster(result, [1, 2]);
    %     selectedIdx2 = recluster(result, [2, 3]);
    %     result.clusterIdx(selectedIdx1 & selectedIdx2 & ~logical(result.noiseClusterIdx)) = v;

    narginchk(1, 3);

    if nargin < 2
        PCShown = [1, 2];
    end

    if nargin < 3
        colors = generateColorGrad(12, 'rgb', 'red', [1, 4, 7, 10], 'green', [2, 5, 8, 11], 'blue', [3, 6, 9, 12]);
    end

    PCx = PCShown(1);
    PCy = PCShown(2);

    Fig = figure;
    maximizeFig(Fig);

    for index = 1:result.K
        idx = find(result.clusterIdx == index);
        x = result.pcaData(idx, PCx);

        if isempty(x)
            continue;
        end

        y = result.pcaData(idx, PCy);
        cx = result.clusterCenter(index, PCx);
        cy = result.clusterCenter(index, PCy);

        colorsAll = repmat(reshape(colors, [length(colors), 1]), ceil(result.K / length(colors)) * length(colors), 1);
        plot(x, y, '.', 'MarkerSize', 12, 'Color', colorsAll{index}, 'DisplayName', ['cluster ' num2str(index)]); hold on;
        h = plot(cx, cy, 'kx', 'LineWidth', 1.2, 'MarkerSize', 15);
        set(get(get(h, 'Annotation'), 'LegendInformation'), 'IconDisplayStyle', 'off');
    end

    % Noise
    idx = find(result.clusterIdx == 0);
    nx = result.pcaData(idx, PCx);
    ny = result.pcaData(idx, PCy);
    plot(nx, ny, 'ko', 'DisplayName', 'Noise');

    % Origin data
    % plot(result.pcaData(:, PCx), result.pcaData(:, PCy), 'k.', 'MarkerSize', 12, 'DisplayName', 'Origin');

    legend;
    title(['Channel: ', num2str(result.chanIdx), ' | nSamples = ', num2str(size(result.wave, 1))]);
    xlabel(['PC-' num2str(PCx)]);
    ylabel(['PC-' num2str(PCy)]);

    %% get boarder
    [xv, yv] = genPolygon(gca);
    selectedIdx = inpolygon(result.pcaData(:, PCx), result.pcaData(:, PCy), xv, yv);

    return;
end
